### ISSUE TITLE
webservice response

### ISSUE THREAD

**Issue by andreas20** [antonraharja/playsms-webservices#4]
I get the response below when I call the webservices. Is there an easy way to parse this in PHP and grab <status> and <smslog_id> ??? I tried with json decode but with no success. If possible provide some PHP code. Thank you..

getToken
stdClass Object
(
    [status] => OK
    [error] => 0
    [token] => 7ebbfd472a1b01e4a44aa00f3e5d18bb
    [error_string] => 
    [timestamp] => 1449580254
)

Send SMS:
stdClass Object
(
    [data] => Array
        (
            [0] => stdClass Object
                (
                    [status] => OK
                    [error] => 0
                    [smslog_id] => 82
                    [queue] => e7b078c6c590ca661d5d309248a9962f
                    [to] => 99xxxxxxx
                )
        )
[error_string] => 
[timestamp] => 1449580254
)

**Comment by antonraharja** [comment]
hi, the webservices returns should be easily decoded by json_decode() to an object or array

ref:
http://php.net/manual/en/function.json-decode.php
