### ISSUE TITLE
Error when the response does not contain data

### ISSUE THREAD

**Issue by cdarken** [antonraharja/playsms-webservices#5]
Because in case of a response like this
```js
{
  +"status": "ERR"
  +"error": "501"
  +"error_string": "no data returned or result is empty"
  +"timestamp": 1483544867
}
```
at this line https://github.com/playsms/playsms-webservices/blob/master/src/Playsms/Webservices.php#L87 you don't check if `$this->data->data` is set there's an error thrown.
If you modify that line like this it works fine:
```php
if (isset($this->data->data) and is_array($this->data->data)) {
```

**Comment by antonraharja** [comment]
merged #6
